
CREATE TABLE CUSTOMERS (
CustomerID INT PRIMARY KEY,
FullName VARCHAR(100),
Email VARCHAR(100), 
Age INT
);

ALTER TABLE CUSTOMERS
MODIFY Email VARCHAR(100) NOT NULL UNIQUE;

ALTER TABLE CUSTOMERS
MODIFY FullName VARCHAR(100) NOT NULL;

ALTER TABLE CUSTOMERS
ADD CONSTRAINT chk_age CHECK (Age >= 0 AND Age <= 120);